### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by codeotter0201**
我是 ender

這是台北一日遊網址
http://52.52.144.73:3000/

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. If we scroll down and up quickly, your code will load the same page multiple times.
2. We have to implement **scrolling effect** on MRT list when we click on arrows.

**Comment by codeotter0201** [comment]
Please check my last commit tks.

**Comment by cwpeng** [comment]
Re-request review so that I can review for you.

**Review by cwpeng — CHANGES_REQUESTED** [review]
We should stop loading more pages if there are no more data.

Screenshot 2023-09-08 141604

**Comment by codeotter0201** [comment]
fix: stop loading page if there are no more data

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
